# Generated by Django 4.1.7 on 2023-03-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutes',
            options={'verbose_name': 'rutes', 'verbose_name_plural': 'rutes'},
        ),
        migrations.DeleteModel(
            name='rute',
        ),
    ]
